### ISSUE TITLE
[Suggestion] Reduce the default limit to 2 hours

### ISSUE THREAD

**Issue by Dylan-86** [mmnaseri/nordvpn-reconnect#4]
Hi,
As to my direct experience, the connection on my end typically drops after 2 hours 30 minutes, give or take 15 minutes.

For this, I've set the timer to 2 hours and I would recommend this as a default value.

Note that the fist time that my connection stopped working I've tried to run nordvpnd-killer.sh but it didn't solve the situation. I had to reboot anyway.

Thanks,
D

**Comment by mmnaseri** [comment]
So, maybe I should also document this better. Running `nordvpnd-killer.sh` doesn't automatically unlock your system. You have to run it, _and_ drop a file asking it to kill the service. That script is meant to be a long-running process which can accommodate your need to unlock yourself at any time. So, run it as `root` with `sudo` or install it as a service and run that, and then ask it to kill the nordvpn daemon for you:

```bash
touch /tmp/nordvpnd-killer.ask
```

**Comment by mmnaseri** [comment]
Updated the default to 2 hours.
